"""Per-chapter review data: which v1 text each new section came from, what changed, the fix log
and the decisions to put to the user."""

DATE = '2 October 2026'

PAGES = {
'ch1': {
 'page_title': 'Chapter 1 Review', 'date': DATE, 'target': '900', 'exhibits': '2 (Exhibits 1 and 2)',
 'drawn': 'v1 Chapters 1, 2 and 3; executive summary', 'fixprefix': 'C1',
 'decide_lede': 'Nothing in this chapter changes a verdict, a learning or a headline number. You asked me to proceed, so I have adopted the proposals below provisionally and carried them into Chapters 2 and 4. Each is easy to reverse: say if you disagree with any.',
 'decide': [
  ('Thai excavators: stop calling them a case where Japanese brands held.',
   'SANY\'s Thai distributor reports it was Thailand\'s top excavator seller in 2020 and 2021 (1,840 units and a 30.4% share in 2021; a company claim, page read 2 Oct 2026). China already supplied about a third of Thai excavator imports in 2015 and 42% in 2025. The flat 2019–24 import share therefore probably means Chinese brands arrived earlier, not that Japan held. This chapter now says only that China\'s share "barely moved". The Thailand verdict (structural in four of five categories) is unchanged, because it rests on import data. <b>Your call:</b> agree to re-evidence failure mode 2 ("A loyal installed base holds") mainly with India (Tata Hitachi\'s dealer base, Indian pumps) when we write Chapter 4, and to drop "Japanese brands held Thai excavators" from the executive summary.'),
  ('Approved text moved out of the body (please confirm).',
   'Three blocks of v1 Chapters 1–3 are cut from the body under the v5 word budget. (1) The overseas-revenue league table (Zoomlion 58.56%, XCMG 48.2%, LiuGong 47.65%, Heli 44%, Hangcha 43.38%) and SANY\'s 31.7% overseas margin go to Appendix B. (2) Of the nine 2026 policy events, the trade agreements (UK–India in force, EU–India awaiting signature), the US Section 122 surcharge and the US excess-capacity investigation go to Appendix A, so they are no longer in the body or among the five signs to watch. (3) The five tests, Japan\'s and Korea\'s losses by country, Vietnam\'s mirror data and the Komatsu and Hitachi share chart go to Appendices A and D, as v5 sets out.'),
  ('The state-support paragraph has no home in v5.',
   'v1 Chapter 3 noted India\'s 30–110% dumping margins on cranes, the EU\'s anti-subsidy duties on access equipment, and that subsidies explain why Chinese firms could push abroad but not how they won customers. We propose one sentence of it in Appendix D (method), with the crane margins kept in Appendix A. Say if you want it back in Chapter 1.'),
 ],
 'sections': {
  '1.1': {'v1': [('exec', None, [2]), ('c2', None), ('c2', "China's share of imports rose almost everywhere")],
          'changes': ['Kept the two approved headline numbers (Indonesia excavators 33% → 75%; India cranes 35% → 93%) and added the third v5 number, robots passing Japan in 2025.',
                      'Kept the 18-of-19 and 12-over-half findings and the heat map (now Exhibit 1). Forklift and excavator patterns shortened to two sentences; crane value detail moves to Appendix A.',
                      'New: the "year China overtook Japan" measure is introduced once here, to be used in Chapter 3.',
                      'Data-limits paragraph shortened; the Indian 95% caution kept. Japan\'s and Korea\'s losses by country (v1 2.2) move to Appendix A.']},
  '1.2': {'v1': [('c1', 'Chinese OEMs now earn half'), ('c1', 'A collapse at home'), ('c1', 'The second layer'), ('c1', 'The rules reset')],
          'changes': ['Restructured around the v5 three-stage timeline (exporting the surplus; going overseas-first; owning the system). The old phase names are not used.',
                      'Turning point 1 is now dated 2022 at company level (SANY 23% → 45.7%), with 2023 as the year exports passed home sales in units (correction 5).',
                      'New: CCMA series back to 2016, showing exports at 7–11% of units to 2020.',
                      'The overseas-revenue league table and the Indonesia US$882m fact move to Appendices B and A. SANY\'s 63% is kept.',
                      'The nine 2026 policy events become one paragraph: India\'s three moves, Indonesia\'s local-content credit and the US forced-labour tariffs. The rest moves to Appendix A (see "For your decision").']},
  '1.3': {'v1': [('exec', None, [3]), ('c2', 'In Indonesia, company disclosures'), ('c3', None), ('c3', 'Five tests'), ('c3', 'Indonesia: share fell'), ('c3', 'India: Chinese gains'), ('c3', 'What about state support?'), ('c3', 'Verdict', [0, 1, 3])],
          'changes': ['Kept the Komatsu argument (29% → 20%, about 750 fewer machines in a market about 4,400 units larger, record coal) and the Hexindo point.',
                      'Kept the verdict word for word in substance: structural in India and Indonesia, and in four of five Thai categories; cycles amplified, did not cause.',
                      'The five tests are named but move to Appendix D; the India test evidence (sales boom, highway cycle) moves to Appendix A; the Indonesia brand chart becomes a sentence.',
                      'New: "China gained where mining plays no part" now includes factory machines, pointing to Chapter 3.',
                      'Thai excavators worded neutrally ("barely moved") pending decision 1.',
                      'State-support paragraph cut (decision 3).']},
  '1.4': {'v1': [('c3', 'Verdict', [2]), ('c5', 'Where it stops working'), ('c1', 'The question for this paper')],
          'changes': ['New section, built from the v1 downturn paragraph and Learning 2\'s limit.',
                      'Coal updated from the top-up: quotas first cut to about 600 Mt, slow work-plan approvals, lenders waiting on approval, and the ministry\'s projection of about 720 Mt (a projection, not a quota).',
                      'Highway pace: 25 km a day in FY26 kept; 21 km a day now labelled as the FY27 expectation.',
                      'The approved central question closes the chapter, as the benchmark checklist asks, with a pointer to Chapters 2–4. "OEM" is defined here once.']},
 },
 'fixes': [
  ('Turning point 1 dated to 2022 at company level; 2023 kept as the year exports passed home sales in units (brief §6, correction 5).', 'SANY FY2022 results, N5; CCMA via refs 49–50'),
  ('Crane duties: "not imposed within the three months its rules allow"; the word "pending" is not used (locked fix F1). The lapse is dated to 2025, not described as a 2026 event.', 'Refs 37, 14; Rule 18(1)'),
  ('US 10% and 12.5% tariffs attributed to the forced-labour trade action effective 24 Jul 2026 (locked fix F2).', 'Ref 67'),
  ('"About 720 Mt" written as the energy ministry\'s projection of 2026 output, not a quota; the quota is described as first cut to about 600 Mt and then revised (correction 9, top-up item 4).', 'Ref 88; N7, N9'),
  ('Final 2025 coal output confirmed at 817 Mt (ESDM 817.48 Mt); an earlier January estimate of 790 Mt is superseded.', 'N6'),
  ('Highway pace: 25 km a day is FY26; 21 km a day is the FY27 expectation (correction 10).', 'Ref 94 (CareEdge, 25 Sep 2026)'),
  ('Thai excavators: "Japan held" wording removed; neutral wording pending your decision.', 'Ref 38; SANY Thaiyont claim (search-verified)'),
  ('Hexindo: v1 said its share "barely moved" in Chapter 3 but "followed a similar path" in Chapter 2. We use the Chapter 2 wording, which matches the 50% → 37% combined-share calculation. To be rechecked against refs 82–83 for Appendix A.', 'Refs 82, 83'),
  ('XCMG Balikpapan described as a base for repairing and rebuilding mining-machine parts, matching ref 24 (overhaul and remanufacturing of components).', 'Ref 24'),
  ('"Five plants and service bases since November 2025" checked against the list: Heli Rayong, Hangcha Chonburi, LiuGong Karawang, XCMG Weda Bay, XCMG Balikpapan.', 'Refs 24, 29–32'),
  ('United Tractors\' Jan–Aug 2026 Komatsu figures (2,689 units, −21%; large mining 436, −49%; locked fix F6) move to Appendix A unchanged. The chapter keeps only the 2027 recovery expectation.', 'Refs 90, 97'),
  ('SANY 2022: v1 research said its overseas margin beat its home margin "for the first time". The release says only that the overseas gross margin (26.4%) was higher than in China (21.9%), so "for the first time" is dropped.', 'N5 (page read)'),
  ('Exports-to-2020 share stated as 7–11% of units, from CCMA 2016–2020. The 2015 share (10.2%) is not used, because the 2015 absolute figures are unsourced.', 'N2–N4, ref 49'),
 ],
},
'ch3': {
 'page_title': 'Chapter 3 Review', 'date': DATE, 'target': '2,000', 'exhibits': '3 (Exhibits 5, 6 and 7)',
 'drawn': 'v1 Chapters 2, 9, 10, 12 and 15, and the box on supporting moves; mostly new evidence', 'fixprefix': 'C3',
 'decide_lede': 'Most of this chapter is new, built from the batch 2 dossiers. Nothing in it changes a verdict, a learning or a headline number. Three judgements are ours; they are adopted provisionally, so say if you want any changed.',
 'decide': [
  ('Our view of the window for each kind of buyer.',
   'Section 3.5 gives a time judgement for each kind of buyer: factories have "a few years at most"; for robots, incumbents have "until about 2030" to lock in installers and service; plant engineers have the longest window. These are our judgements from the crossover years and the pattern in factory machines, labelled "in our view". Agree, soften, or ask for ranges.'),
  ('Two new rows in the approved "our view by category" table.',
   'Factory machines (new) and Robots (replacing v1\'s "Robotics and automation: inconclusive"). The "What would change it" column now points to the five v5 signs, not the eight v1 signposts. Signs that dropped out of the body (the battery-cost gap, Press Note 2 approvals, coal quotas, the US excess-capacity case) are no longer cited.'),
  ('Indonesia\'s 62% robot share is shown but not relied on.',
   'Re-pulled from UN Comtrade: the jump is lumpy, with US$51m of the US$61m from China arriving in September to December 2025 and US$30m in October alone. That fits one or more large plant fit-outs. The headline "overtook Japan in all four markets" still holds on India, Thailand and Malaysia alone (China 37% against Japan 31% in 2025). We name BYD\'s Subang plant as a possible cause, marked unconfirmed. Say if you would rather leave the cause out.'),
 ],
 'sections': {
  '3.1': {'v1': [('c2', 'Categories follow a common sequence')],
          'changes': ['Replaces v1\'s "category maturity ladder" (four equipment families) with the v5 three kinds of buyer.',
                      'The crossover years are new, from the 2015–2025 trade series (four markets). Machine tools are split, because machining centres have not crossed.',
                      'States the approved Chapter 3 qualifier: in the next products the same moves arrive in a different order, and the buyer decides the order.']},
  '3.2': {'v1': [('box', None, [0]), ('c12', "Chinese investment is changing", [0])],
          'changes': ['New section. v1 could only call "following home-country customers" plausible (box). It is now evidenced by Haitian\'s own results statement and by trade gains where Chinese investment is heaviest.',
                      'Thai industrial-estate figure (6% → 17%) carried over from v1 Chapter 12.',
                      'Company plant claims are labelled, and the Haitian claim carries the regulator\'s caution (correction 15).',
                      'Adds India\'s two imposed duties (lasers 2023; plastic-moulding machines 2025) and the incumbent petitioners, which Chapter 4 uses again.']},
  '3.3': {'v1': [('c9', 'Where it stops working')],
          'v1_none': 'v1 had no trade measure for robots (Appendix A.1) and rated robotics "inconclusive" (Chapter 15). Its robot evidence was limited to the sentences shown here and India\'s installation count in Chapter 10.',
          'changes': ['New section on the 2025 turn: China\'s customs data and the importers\' trade data.',
                      'Keeps v1\'s point that the home lead does not travel automatically (Estun\'s falling overseas share), now cited to the HKEX annual results.',
                      'Adds the routes in (the Thai joint venture with a local auto-parts maker; the BOI-approved parts cluster) and the incumbents\' move to the US.',
                      'Warehouse robots get one box, as v5 asks. Efort moves to Chapter 4 (failure modes 4 and 6).']},
  '3.4': {'v1': [('c10', 'Compressors, pumps and robots'), ('c2', "China's share of imports rose almost everywhere", [3])],
          'changes': ['Compressors and pumps now use the four-market 2015–2025 series rather than single-country 2019–24 shares.',
                      'Kaishan\'s small Indian sales against about US$500m of imports from China show that the flow is mostly unbranded.',
                      'ELGi: the low-cost range and its separate distributor network are kept. The "25–30% of Indian volume" management estimate is dropped from the body (correction 12).',
                      'New: Atlas Copco\'s Chinese brands, with Liutech\'s distributors in four ASEAN markets (top-up item 6).',
                      'ELGi\'s motor in-sourcing and Indian robot installs move out (Appendix B; robots to 3.3).']},
  '3.5': {'v1': [('c15', 'Three paths'), ('c15', 'Our view by category')],
          'changes': ['The "three paths" scenarios are dropped from the body. They are replaced by a window for each kind of buyer.',
                      'The approved "our view by category" table is kept, with Factory machines added and the Robots row rewritten.',
                      'New: which moves do not travel (customer credit, except as subscription in warehouse robots), from the dossiers.']},
 },
 'fixes': [
  ('Haitian\'s Indian plant is not presented as proof of local production; the regulator\'s record is quoted (correction 15).', 'N16 (paras 47(l), 54)'),
  ('Estun figures cited to the HKEX annual results, not the Sina AI summary (correction 13). v1 ref 86 is retired.', 'N22'),
  ('Estun\'s segment growth differs between sources. v1\'s Part II introduction used robots +31.80% and components −8.72% (Sina); the HKEX results give +31.91% and −8.99%. Use the HKEX figures wherever the point reappears (Chapter 2 or Appendix B).', 'N22'),
  ('Inovance\'s "about 6%" overseas share is labelled secondary (correction 11). Its primary statement on winning top customers in Vietnam is added. Open item: name the secondary source, or drop the 6%.', 'N23'),
  ('Chinese suppliers\' share of China\'s robot market: 55% in 2025, down from 57% (correction 6).', 'Ref 85'),
  ('India compressors: the rise came mainly in 2024 (52.6%), and 2025 was 49.3% (correction 8).', 'Ref 71; N1'),
  ('India rescinded the machinery Omnibus regulation; the pumps quality-control order is described as a draft, as no final notification was found (correction 7; top-up item 3).', 'Ref 57; N33'),
  ('ELGi\'s 25–30% estimate is not used in the body. If it returns in Appendix B, it will be labelled a company estimate, not comparable with import shares (correction 12).', 'Refs 145–147'),
  ('ELGi\'s low-cost range: "scheduled the launch for September 2026". The August call did not confirm that the launch had happened.', 'N34'),
  ('Indonesia\'s 62% robot share flagged as unexplained; the headline rests on the other three markets (top-up item 1).', 'N1'),
  ('India\'s laser duties: case opened Oct 2022; final findings 27 Sep 2023; duty imposed 22 Dec 2023, five years. Rates as notified.', 'N18'),
  ('Chen Hsong\'s 27% applies to its Chinese plant; its Taiwan plant pays 39%.', 'N17'),
  ('Plastic-moulding imports "from under 4% to 19% of Indian demand" attributed to the Indian producers who brought the case, as in the record.', 'N16 (para 106(t))'),
  ('Thai industrial-estate share rounded from 17.06% to 17%.', 'Ref 135'),
  ('Generator sets in Malaysia: the data-centre link is stated as unproven.', 'N1; evidence log'),
  ('Hai Robotics\' Penang production site (Sep 2025) added. The dossier said warehouse robots had "no regional plants" (top-up item 10).', 'N29'),
  ('Haitian\'s overseas share is 42.9% (RMB7,601.5m of RMB17,733.2m), as the HKEX announcement prints it, not 42.8%. The quote now uses the filing\'s English wording ("the global expansion of Chinese enterprises").', 'N10 (filing read)'),
  ('India\'s laser case opened on 29 Sep 2022, not October 2022 (October was the press report). The final findings show imports from China at 78–83% of Indian demand from 2018-19 to 2021-22.', 'N39 (filing read)'),
  ('New: Haitian\'s annual report carries a provision of INR1,859m (RMB146m) for an Indian customs anti-dumping claim against its Indian unit, unchanged from 2024.', 'N38 (filing read)'),
  ('Indonesia\'s robot jump is shown to be lumpy (US$30m from China in October 2025). The three-market figure without Indonesia is 21% → 37% for China and 35% → 31% for Japan.', 'N1 (re-pulled)'),
  ('Atlas Copco: Liutech\'s own site shows dedicated product ranges for India and Southeast Asia. This replaces the distributor list, which the site no longer shows.', 'N36 (pages read)'),
  ('Hai Robotics: "with a manufacturing partner" dropped. The article confirms the Penang factory, not who runs it.', 'N29 (page read)'),
  ('Hengli is not used in the body. When it appears in Appendix B, its overseas share is about 19% (overseas sales RMB2,106m, +1.6%, against RMB8,750m at home), not "over 35%" (top-up item 5).', 'Hengli 2025 annual report, segment table (filing read)'),
 ],
},
}
